# Path to your oh-my-zsh installation.
export ZSH=/Users/home/.oh-my-zsh

# NVM
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# NODE 8
export PATH="/usr/local/opt/node@8/bin:$PATH"

# Mongodb@3.4
# Startupflow only
export PATH="/usr/local/opt/mongodb@3.4/bin:$PATH"

ZSH_THEME="ys"

plugins=(
  osx
  git
  dotenv
  bundler
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh_aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/elasticsearch@5.6/bin:$PATH"
